/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "structureboxes-parent"
include(":structureboxes-core")
include(":structureboxes-factionsuuid")
include(":structureboxes-bukkit")
//include(":structureboxes-sponge")
project(":structureboxes-core").projectDir = file("StructureBoxes-Core")
project(":structureboxes-factionsuuid").projectDir = file("StructureBoxes-FactionsUUID")
project(":structureboxes-bukkit").projectDir = file("StructureBoxes-Bukkit")
//project(":structureboxes-sponge").projectDir = file("StructureBoxes-Sponge")
