/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

repositories {
    mavenLocal()
}
dependencies {
    api("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
    api(project(":structureboxes-core"))
    compileOnly("dev.kitteh:factionsuuid:0.7.4")
    //compileOnly(files("/../libs/bukkit/FactionsUUID/Factions.jar"))
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-FactionsUUID"
