/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

repositories {
    maven("https://maven.enginehub.org/repo/")
}

dependencies {
    implementation("com.sk89q.worldedit:worldedit-core:7.3.10-SNAPSHOT")
    implementation("net.kyori:adventure-api:4.22.0")
    implementation("net.kyori:adventure-text-serializer-plain:4.22.0")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-Core"
