/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.goooler.shadow") version "8.1.8"
    id("buildlogic.java-conventions")
    //id("io.github.0ffz.github-packages") version "1.2.1" // This plugin will allow us to authenticate to GitHub Packages automatically.
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))


repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/repositories/snapshots")
    maven("https://oss.sonatype.org/content/repositories/central")
    //mavenLocal() // This is needed for CraftBukkit and Spigot.
    maven("https://jitpack.io")
    maven("https://nexus.iridiumdevelopment.net/repository/maven-releases/")
    maven("https://maven.enginehub.org/repo/")
    maven("https://repo.bg-software.com/repository/api/")


}


dependencies {
    implementation(project(":structureboxes-core"))
    runtimeOnly(project(":structureboxes-factionsuuid"))
    //paperweight.paperDevBundle("1.21.4-R0.1-SNAPSHOT")
    api("io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT")
    api("com.sk89q.worldedit:worldedit-bukkit:7.3.10-SNAPSHOT")
    api("com.sk89q.worldguard:worldguard-bukkit:7.0.13-SNAPSHOT")
    implementation("com.github.TownyAdvanced.Towny:towny:0.101.1.7")
    implementation(platform("com.intellectualsites.bom:bom-newest:1.52"))
    api("com.intellectualsites.plotsquared:plotsquared-core:7.5.1")
    api("com.intellectualsites.plotsquared:plotsquared-bukkit:7.5.1") { isTransitive = false }
    compileOnly("com.github.Angeschossen:LandsAPI:7.13.1")
    api(files(
        "/../libs/bukkit/MassiveCore.jar",
        "/../libs/bukkit/Factions.jar",
        "/../libs/bukkit/civs.jar",
        "/../libs/bukkit/GriefPrevention.jar",
        "/../libs/bukkit/LandClaiming.jar",
        "/../libs/bukkit/Movecraft_8.0.0_beta-5.jar",
        "/../libs/bukkit/RedProtect-8.1.2-SNAPSHOT-b444-Spigot.jar",
        "/../libs/bukkit/SuperiorSkyblock2-2024.4.jar",
        "/../libs/bukkit/skyblock/acidisland.jar",
        "/../libs/bukkit/skyblock/askyblock.jar",
        "/../libs/bukkit/skyblock/bentobox-1.15.2.jar",
        "/../libs/bukkit/skyblock/IridiumSkyblock-2.6.0.jar",
        "/../libs/bukkit/skyblock/IslandWorld.jar",
        "/../libs/bukkit/skyblock/SkyBlock.jar"
    ))
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-Bukkit"
