name: StructureBoxes
main: io.github.eirikh1996.structureboxes.StructureBoxes
version: '3.2'
api-version: 1.13
author: eirikh1996
depend:
  - WorldEdit
softdepend:
  - WorldGuard
  - RedProtect
  - Factions
  - Civs
  - Lands
  - LandClaiming
  - GriefPrevention
  - Kingdoms
  - Towny
  - Movecraft
  - PlotSquared
  - IridiumSkyblock
  - SkyBlock
  - BentoBox
  - SuperiorSkyblock
  - IslandWorld
  - AcidIsland
  - ASkyBlock
commands:
  structurebox:
    aliases:
      - sb
      - sbox
    usage: /structurebox <create|reload|undo>
permissions:
  structureboxes.undo:
    default: true