import org.spongepowered.gradle.plugin.config.PluginLoaders

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("java-library")
    id("org.spongepowered.gradle.plugin") version "2.0.2"
}

repositories {
    mavenCentral()
    maven("https://repo.spongepowered.org/repository/maven-public/")
    maven("https://maven.enginehub.org/repo/")
}

group = "io.github.eirikh1996"
version = "3.0"
description = "Here lies an example plugin definition"

sponge {
    apiVersion("13.0.0")
    loader {
        name(PluginLoaders.JAVA_PLAIN)
        version("1.0")
    }
    license("GNU General Public License v3")
    plugin("structureboxes") {
        displayName("StructureBoxes")
        version("3.0")

    }
}

dependencies {
    api(project(":structureboxes-core"))
    api("com.sk89q.worldedit:worldedit-sponge:7.2.1")
    compileOnly("org.bstats:bstats-sponge:3.1.0")
    compileOnly(files(
        "/../libs/sponge/movecraft-0.4.1.jar",
        "/../libs/sponge/EagleFactions-1.2.0-API-11.0.0.jar",
        ))
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-Sponge"
