/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.sk89q.worldedit.worldedit.sponge)
    api(project(":structureboxes-core"))
    api(libs.org.spongepowered.configurate.yaml)
    compileOnly("org.bstats:bstats:1.8")
    compileOnly(libs.org.spongepowered.spongeapi)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-Sponge"
