import org.spongepowered.gradle.plugin.config.PluginLoaders

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("com.gradleup.shadow") version "8.3.5"
    id("java-library")
    id("org.spongepowered.gradle.plugin") version "2.3.0"
}

repositories {
    mavenCentral()
    maven("https://repo.spongepowered.org/repository/maven-public/")
    maven("https://maven.enginehub.org/repo/")
}

group = "io.github.eirikh1996"
version = "3.0"
description = "Here lies an example plugin definition"

sponge {
    apiVersion("13.0.0")
    loader {
        name(PluginLoaders.JAVA_PLAIN)
        version("1.0")
    }
    license("GNU General Public License v3")
    plugin("structureboxes") {
        displayName("StructureBoxes")
        version("3.0")
        links {
            homepage("https://ore.spongepowered.org/eirikh1996/Structure-Boxes")
            source("https://github.com/eirikh1996/StructureBoxes")
            issues("https://github.com/eirikh1996/StructureBoxes/issues")
        }
        contributor("eirikh1996") {
            description("Lead Developer")
        }
        entrypoint("io.github.eirikh1996.structureboxes.StructureBoxes")
    }
}

tasks.shadowJar {
    archiveBaseName.set("StructureBoxes-Sponge")
    archiveClassifier.set("")
    archiveVersion.set("")
    dependencies {
        include(project(":structureboxes-core"))
        include(dependency("org.bstats:bstats-sponge:3.1.0"))
        include(dependency("org.bstats:bstats-base:3.1.0"))
    }
    relocate("org.bstats", "io.github.eirikh1996.structureboxes.metrics")
}

dependencies {
    api(project(":structureboxes-core"))
    api("org.bstats:bstats-base:3.1.0")
    api("org.bstats:bstats-sponge:3.1.0")
    compileOnly(files(
        "/../libs/sponge/movecraft-0.4.1.jar",
        "/../libs/sponge/EagleFactions-1.2.0-API-11.0.0.jar",
        "/../libs/sponge/worldedit-sponge-api14-7.3.12-SNAPSHOT-dist.jar"
        ))
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

description = "StructureBoxes-Sponge"
